name: magarena # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.96' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single player collectable card game
description: |
  Single player collectable card game

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  magarena_icon.png
title: Magarena

apps:
  magarena:
    command: Magarena.sh
parts:
  magarena:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      magarena: build/
      magarena.1: man/man1/

architectures:
  - build-on: amd64

